spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookkeeping?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1900130214
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.xx.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl